### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by 187jjay187** [187jjay187/react-gp#25]
Here is a link to my github repo that we will be working on 
- Kanban Board Link: " [Kanban Board](https://github.com/187jjay187/react-gp/projects/1) "

In this React Group Project there is only two coding partners:
- Developer 1: [Jerome (Jay) G.O. ](https://github.com/187jjay187)
- Developer 2: [Usama Masood](https://github.com/usamamaliq)

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @187jjay187,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You are required to provide the link to your Kanban project, instead of your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ichala** [comment]
Hi Team
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- All tasks created   ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑  Kindly make sure all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below: _**
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/89282221/210231164-38c1aeab-2dc4-47c1-a38c-0bdfe1a18a7e.png">







## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @187jjay187 & @usamamaliq, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to start working on it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
